<?php
/** @var \MageSuite\CmsProductBacklink\Block\Backlink $block */
$cmsPages = $block->getCmsPages();
$configuration = $block->getData();
$title = $configuration['title'] ?? __('CMS Pages');
$subtitle = $configuration['subtitle'] ?? null;
$componentHtml = '';

if ($cmsPages) {
    $configuration = [
        'type' => 'cms-teaser',
        'data' => array_merge(
            [
                'ids' => $cmsPages,
                'limit' => 1000,
                'tags' => '',
                'mix' => ' cs-image-teaser--backlink'
            ],
            $configuration['data'] ?? []
        )
    ];
    $componentHtml = $block->getComponentHtml($configuration);
}

if ($componentHtml) { ?>
    <?= $block->getLayout()->createBlock(
        '\Creativestyle\ContentConstructorFrontendExtension\Block\Component', 'pdp-cms-backlink-headline', [
            'data' => [
                'section' => 'content',
                'type' => 'headline',
                'data' => [
                    'title' => $title,
                    'subtitle' => $subtitle,
                    'mix' => ' cs-headline--backlink',
                ]
            ],
        ]
    )->toHtml(); ?>
    <?= $componentHtml; ?>
<?php } ?>