<?php
/** @var \MageSuite\CmsProductBacklink\Block\Backlink $block */
$cmsPages = $block->getCmsPages();
$configuration = $block->getData();
$componentHtml = '';

if ($cmsPages) {
    $configuration = [
        'type' => 'cms-teaser',
        'data' => array_merge(
            [
                'ids' => $cmsPages,
                'limit' => 1000,
                'tags' => '',
                'mix' => ' cs-image-teaser--backlink'
            ],
            $configuration['data'] ?? []
        )
    ];
    $componentHtml = $block->getComponentHtml($configuration);
}

if ($componentHtml) {
    echo $componentHtml;
} ?>